// This file was originally a .ts file.
// interface Notification {
//     title: String,
//     description: String,
//     type: 'success' | 'danger' | 'warning' | 'info' | 'primary' | 'secondary',
//     key: String // Do not fill, generated by this plugin
// }

import { reactive } from 'vue';
import genKey from './genKey';

const notifications = {
    notifications: reactive([]),

    push(notification) {
        notification.key = genKey();
        notifications.notifications.push(notification);
        setTimeout(() => {
            const index = notifications.notifications.findIndex(
                (item) => item.key === notification.key
            );
            if (index !== -1) {
                notifications.notifications.splice(index, 1);
            }
        }, 4000);
    },

    remove(index) {
        notifications.notifications.splice(index, 1);
    },
};

export default notifications;

export const NotificationsPlugin = {
    install: (app) => {
        app.config.globalProperties.$notifications = notifications;
    },
};

export const { push, remove } = notifications;
