// This file was originally a .ts file.
// interface Snackbar {
//     title: String,
//     description: String,
//     postText: String,
//     type: 'success' | 'danger' | 'warning' | 'info' | 'primary' | 'secondary',
//     key: String // Do not fill, generated by this plugin
// }

import { reactive } from 'vue';
import genKey from './genKey';

let previousTimeout = null;

const snackbars = {
    snackbars: reactive([]),

    push(snackbar) {
        clearTimeout(previousTimeout);
        snackbar.key = genKey();
        snackbars.snackbars.splice(0, 1, snackbar);

        previousTimeout = setTimeout(() => {
            snackbars.snackbars.pop();
        }, 4000)
        // const index = snackbars.snackbars.findIndex(
        //     (item) => item.key === snackbar.key
        // );
        // if (index !== -1) {
        //     snackbars.snackbars.splice(index, 1);
        // }
    },

    remove(index) {
        snackbars.snackbars.splice(index, 1);
    },
};

export default snackbars;

export const SnackbarsPlugin = {
    install: (app) => {
        app.config.globalProperties.$snackbars = snackbars;
    },
};

export const { push, remove } = snackbars;
