export default [
    // Use maphelpers buildInfrastructureAssetLayers instead
    // {
    //     id: 'infrastructure-asset-lines',
    //     type: 'line',
    //     'source-layer': 'infrastructure_asset_linestrings',
    //     minzoom: 11,
    //     layout: {
    //         'line-cap': 'round',
    //         'line-join': 'round',
    //     },
    //     paint: {
    //         'line-color': [
    //             'case',
    //             ['boolean', ['feature-state', 'hover'], false],
    //             '#D68724',
    //             ['boolean', ['feature-state', 'selected'], false],
    //             '#4683E7',
    //             '#552ab2',
    //         ],
    //         'line-width': [
    //             'interpolate',
    //             ['linear'],
    //             ['zoom'],
    //             12,
    //             1.75,
    //             13,
    //             2,
    //         ],
    //     },
    // },
    // {
    //     id: 'infrastructure-asset-points',
    //     type: 'circle',
    //     'source-layer': 'infrastructure_asset_points',
    //     minzoom: 11,
    //     paint: {
    //         'circle-radius': [
    //             'interpolate',
    //             ['linear'],
    //             ['zoom'],
    //             6,
    //             1.75,
    //             16,
    //             2,
    //             17,
    //             8,
    //         ],
    //         'circle-color': [
    //             'case',
    //             ['boolean', ['feature-state', 'hover'], false],
    //             '#D68724',
    //             ['boolean', ['feature-state', 'upstream'], false],
    //             '#00ff00',
    //             ['boolean', ['feature-state', 'downstream'], false],
    //             '#ff0000',
    //             ['boolean', ['feature-state', 'selected'], false],
    //             '#4683E7',
    //             '#552ab2',
    //         ],
    //     },
    // },
    // {
    //     id: 'infrastructure-asset-lines-labels',
    //     type: 'symbol',
    //     'source-layer': 'infrastructure_asset_linestrings',
    //     minzoom: 16,
    //     layout: {
    //         'symbol-placement': 'line-center',
    //         'text-offset': [0, 1],
    //         'text-field': '{reference}',
    //         'text-size': 11,
    //         'text-rotation-alignment': 'map',
    //         'text-font': ['Noto Sans Regular'],
    //     },
    //     paint: {
    //         'text-halo-color': 'rgba(255,255,255,1)',
    //         'text-halo-width': 2,
    //     },
    // },
    // {
    //     id: 'infrastructure-asset-points-labels',
    //     type: 'symbol',
    //     'source-layer': 'infrastructure_asset_points',
    //     minzoom: 16,
    //     layout: {
    //         'text-field': '{reference}',
    //         'text-size': 11,
    //         'text-letter-spacing': 0.05,
    //         'text-offset': [0, -1],
    //         'text-font': ['Noto Sans Regular'],
    //     },
    //     paint: {
    //         'text-halo-color': 'rgba(255,255,255,1)',
    //         'text-halo-width': 2,
    //     },
    // },
    // {
    //     id: 'work-package-polygons-labels',
    //     type: 'symbol',
    //     source: 'work-package-polygons',
    //     'source-layer': 'work-package-polygons',
    //     maxzoom: 11,
    //     layout: {
    //         'text-field': '{title}',
    //         'text-size': 16,
    //         'text-font': ['Noto Sans Regular'],
    //     },
    //     paint: {
    //         'text-halo-color': 'rgba(255,255,255,1)',
    //         'text-halo-width': 2,
    //     },
    // },
];
